[project]
name = "material"
version = "0.1.0"
description = "Modern Material Design framework for Django"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2",
    "django-cotton>=2.0.0",
]

[dependency-groups]
dev = [
    "django-stubs>=5.1.3",
    "ipdb>=0.13.13",
]

[tool.pyright]
include = ["material", ]
exclude = ["**/node_modules", "**/__pycache__"]
typeCheckingMode = "basic"
useLibraryCodeForTypes = true
reportMissingImports = true
reportMissingTypeStubs = false
venvPath = "."
venv = ".venv"
