# Generated by Django 3.2 on 2021-11-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0002_i18n'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='gay_friendly',
            field=models.BooleanField(null=True, verbose_name='gay friendly'),
        ),
    ]
