# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_i18n'),
    ]

    operations = [
        migrations.AddField(
            model_name='deptemp',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Avatar'),
        ),
    ]
