# Generated by Django 5.2 on 2025-05-08 11:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="City name", max_length=250, verbose_name="name"),
                ),
                (
                    "is_capital",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the capital city of the country",
                        verbose_name="is capital city",
                    ),
                ),
                (
                    "population",
                    models.BigIntegerField(
                        help_text="Number of inhabitants",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="population",
                    ),
                ),
            ],
            options={
                "verbose_name": "city",
                "verbose_name_plural": "cities",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Ocean",
            fields=[
                (
                    "name",
                    models.CharField(
                        help_text="Ocean name",
                        max_length=250,
                        primary_key=True,
                        serialize=False,
                        verbose_name="name",
                    ),
                ),
                (
                    "area",
                    models.BigIntegerField(
                        help_text="Area in km²",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="area",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(help_text="URL-friendly identifier", verbose_name="slug"),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of the ocean", verbose_name="description"
                    ),
                ),
                (
                    "map_url",
                    models.URLField(help_text="URL to a map of the ocean", verbose_name="map url"),
                ),
            ],
            options={
                "verbose_name": "ocean",
                "verbose_name_plural": "oceans",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Continent",
            fields=[
                (
                    "name",
                    models.CharField(
                        help_text="Continent name",
                        max_length=250,
                        primary_key=True,
                        serialize=False,
                        verbose_name="name",
                    ),
                ),
                (
                    "area",
                    models.BigIntegerField(
                        help_text="km²",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="area",
                    ),
                ),
                (
                    "population",
                    models.BigIntegerField(
                        help_text="Number of inhabitants",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="population",
                    ),
                ),
                (
                    "population_density",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="people/km²",
                        max_digits=8,
                        verbose_name="population density",
                    ),
                ),
                (
                    "longest_river",
                    models.CharField(
                        blank=True,
                        help_text="Name of the longest river",
                        max_length=250,
                        null=True,
                        verbose_name="longest river",
                    ),
                ),
                (
                    "biggest_mountain",
                    models.CharField(
                        blank=True,
                        help_text="Name of the highest mountain",
                        max_length=250,
                        null=True,
                        verbose_name="biggest mountain",
                    ),
                ),
                (
                    "hemisphere",
                    models.CharField(
                        choices=[("NORTH", "North"), ("SOUTH", "South"), ("BOTH", "Both")],
                        help_text="Hemisphere location",
                        max_length=5,
                        verbose_name="hemisphere",
                    ),
                ),
                (
                    "biggest_city",
                    models.OneToOneField(
                        blank=True,
                        help_text="Largest city by population",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="atlas.city",
                        verbose_name="biggest city",
                    ),
                ),
            ],
            options={
                "verbose_name": "continent",
                "verbose_name_plural": "continents",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Country code (3 letters)",
                        max_length=3,
                        unique=True,
                        verbose_name="code",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Country name", max_length=250, verbose_name="name"),
                ),
                (
                    "independence_day",
                    models.DateField(
                        blank=True,
                        help_text="Date of independence",
                        null=True,
                        verbose_name="independence day",
                    ),
                ),
                (
                    "democratic_status",
                    models.BooleanField(
                        help_text="Whether the country is considered a democracy",
                        null=True,
                        verbose_name="democratic status",
                    ),
                ),
                (
                    "continent",
                    models.ForeignKey(
                        help_text="Continent where this country is located",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="countries",
                        to="atlas.continent",
                        verbose_name="continent",
                    ),
                ),
            ],
            options={
                "verbose_name": "country",
                "verbose_name_plural": "countries",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="continent",
            name="largest_country",
            field=models.OneToOneField(
                blank=True,
                help_text="Largest country by area",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="atlas.country",
                verbose_name="largest country",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="country",
            field=models.ForeignKey(
                help_text="Country this city belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="atlas.country",
                verbose_name="country",
            ),
        ),
        migrations.AddField(
            model_name="continent",
            name="oceans",
            field=models.ManyToManyField(
                help_text="Oceans bordering this continent", to="atlas.ocean", verbose_name="oceans"
            ),
        ),
        migrations.CreateModel(
            name="Sea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Sea name", max_length=250, verbose_name="name"),
                ),
                (
                    "area",
                    models.BigIntegerField(
                        help_text="km²",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="area",
                    ),
                ),
                (
                    "avg_depth",
                    models.IntegerField(
                        blank=True,
                        help_text="meters",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="average depth",
                    ),
                ),
                (
                    "max_depth",
                    models.IntegerField(
                        blank=True,
                        help_text="meters",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="maximum depth",
                    ),
                ),
                (
                    "basin_countries",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Countries that border this sea",
                        related_name="seas",
                        to="atlas.country",
                        verbose_name="basin countries",
                    ),
                ),
                (
                    "ocean",
                    models.ForeignKey(
                        help_text="Ocean this sea belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seas",
                        to="atlas.ocean",
                        verbose_name="ocean",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent sea if this is a sub-sea",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_seas",
                        to="atlas.sea",
                        verbose_name="parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "sea",
                "verbose_name_plural": "seas",
                "ordering": ["name"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="city",
            unique_together={("name", "country")},
        ),
    ]
